export default {
    "400": {
        "HASH_INVALID": "The provided hash is invalid.",
        "PHONE_CODE_EMPTY": "phone_code is missing.",
        "PHONE_CODE_EXPIRED": "The phone code you provided has expired.",
        "PHONE_NUMBER_OCCUPIED": "The phone number is already in use.",
        "CHANNELS_ADMIN_PUBLIC_TOO_MUCH": "You're admin of too many public channels, make some channels private to change the username of this channel.",
        "CHANNEL_INVALID": "The provided channel is invalid.",
        "CHAT_ID_INVALID": "The provided chat id is invalid.",
        "USERNAME_INVALID": "The provided username is not valid.",
        "CODE_INVALID": "Code invalid.",
        "EMAIL_HASH_EXPIRED": "Email hash expired.",
        "CODE_HASH_INVALID": "Code hash invalid.",
        "THEME_MIME_INVALID": "The theme's MIME type is invalid.",
        "RESET_REQUEST_MISSING": "No password reset is in progress.",
        "PUBLIC_KEY_REQUIRED": "A public key is required.",
        "PEER_ID_INVALID": "The provided peer id is invalid.",
        "PASSWORD_HASH_INVALID": "The provided password hash is invalid.",
        "PRIVACY_KEY_INVALID": "The privacy key is invalid.",
        "TMP_PASSWORD_DISABLED": "The temporary password is disabled.",
        "WALLPAPER_INVALID": "The specified wallpaper is invalid.",
        "TOKEN_INVALID": "The provided token is invalid.",
        "WEBPUSH_AUTH_INVALID": "The specified web push authentication secret is invalid.",
        "WEBPUSH_KEY_INVALID": "The specified web push elliptic curve Diffie-Hellman public key is invalid.",
        "WEBPUSH_TOKEN_INVALID": "The specified web push token is invalid.",
        "CHANNEL_PRIVATE": "You haven't joined this channel/supergroup.",
        "PASSWORD_REQUIRED": "A 2FA password must be configured to use Telegram Passport.",
        "PHONE_NUMBER_BANNED": "The provided phone number is banned from telegram.",
        "EMAIL_INVALID": "The specified email is invalid.",
        "PHONE_NUMBER_INVALID": "The phone number is invalid.",
        "TTL_DAYS_INVALID": "The provided TTL is invalid.",
        "AUTOARCHIVE_NOT_AVAILABLE": "The autoarchive setting is not available at this time: please check the value of the autoarchive_setting_available field in client config » before calling this method.",
        "PRIVACY_TOO_LONG": "Too many privacy rules were specified, the current limit is 1000.",
        "PRIVACY_VALUE_INVALID": "The specified privacy rule combination is invalid.",
        "MSG_ID_INVALID": "Invalid message ID provided.",
        "SETTINGS_INVALID": "Invalid settings were provided.",
        "EMAIL_UNCONFIRMED_%d": "The provided email isn't confirmed, %d is the length of the verification code that was just sent to the email: use account.verifyEmail to enter the received verification code and enable the recovery email.",
        "EMAIL_UNCONFIRMED": "Email unconfirmed.",
        "NEW_SALT_INVALID": "The new salt is invalid.",
        "NEW_SETTINGS_INVALID": "The new password settings are invalid.",
        "SRP_ID_INVALID": "Invalid SRP ID provided.",
        "SRP_PASSWORD_CHANGED": "Password has changed.",
        "ABOUT_TOO_LONG": "About string too long.",
        "FIRSTNAME_INVALID": "The first name is invalid.",
        "THEME_INVALID": "Invalid theme provided.",
        "CHAT_ADMIN_REQUIRED": "You must be an admin in this chat to do this.",
        "CHAT_NOT_MODIFIED": "The pinned message wasn't modified.",
        "USERNAME_NOT_MODIFIED": "The username was not modified.",
        "USERNAME_OCCUPIED": "The provided username is already occupied.",
        "THEME_FILE_INVALID": "Invalid theme file provided.",
        "WALLPAPER_FILE_INVALID": "The specified wallpaper file is invalid.",
        "WALLPAPER_MIME_INVALID": "The specified wallpaper MIME type is invalid.",
        "AUTH_TOKEN_EXPIRED": "The authorization token has expired.",
        "AUTH_TOKEN_INVALIDX": "The specified auth token is invalid.",
        "PASSWORD_RECOVERY_EXPIRED": "The recovery code has expired.",
        "DC_ID_INVALID": "The provided DC ID is invalid.",
        "API_ID_INVALID": "API ID invalid.",
        "AUTH_BYTES_INVALID": "The provided authorization is invalid.",
        "USER_ID_INVALID": "The provided user ID is invalid.",
        "ACCESS_TOKEN_EXPIRED": "Access token expired.",
        "ACCESS_TOKEN_INVALID": "Access token invalid.",
        "API_ID_PUBLISHED_FLOOD": "This API id was published somewhere, you can't use it now.",
        "AUTH_TOKEN_ALREADY_ACCEPTED": "The specified auth token was already accepted.",
        "AUTH_TOKEN_INVALID": "The specified auth token is invalid.",
        "CODE_EMPTY": "The provided code is empty.",
        "PASSWORD_EMPTY": "The provided password is empty.",
        "PASSWORD_RECOVERY_NA": "No email was set, can't recover password via email.",
        "PHONE_CODE_HASH_EMPTY": "phone_code_hash is missing.",
        "PHONE_CODE_INVALID": "The provided phone code is invalid.",
        "PHONE_NUMBER_UNOCCUPIED": "The phone number is not yet being used.",
        "LASTNAME_INVALID": "The last name is invalid.",
        "PHONE_NUMBER_FLOOD": "You asked for the code too many times.",
        "QUERY_ID_INVALID": "The query ID is invalid.",
        "METHOD_INVALID": "The specified method is invalid.",
        "PARTICIPANTS_TOO_FEW": "Not enough participants.",
        "CHANNELS_ADMIN_LOCATED_TOO_MUCH": "The user has reached the limit of public geogroups.",
        "CHANNELS_TOO_MUCH": "You have joined too many channels/supergroups.",
        "CHAT_ABOUT_TOO_LONG": "Chat about too long.",
        "CHAT_TITLE_EMPTY": "No chat title provided.",
        "PARTICIPANT_ID_INVALID": "The specified participant ID is invalid.",
        "ADMINS_TOO_MUCH": "There are too many admins.",
        "ADMIN_RANK_EMOJI_NOT_ALLOWED": "An admin rank cannot contain emojis.",
        "ADMIN_RANK_INVALID": "The specified admin rank is invalid.",
        "BOTS_TOO_MUCH": "There are too many bots in this chat/channel.",
        "BOT_CHANNELS_NA": "Bots can't edit admin privileges.",
        "BOT_GROUPS_BLOCKED": "This bot can't be added to groups.",
        "INPUT_USER_DEACTIVATED": "The specified user was deleted.",
        "USERS_TOO_MUCH": "The maximum number of users has been exceeded (to create a chat, for example).",
        "USER_BLOCKED": "User blocked.",
        "USER_CREATOR": "You can't leave this channel, because you're its creator.",
        "USER_ADMIN_INVALID": "You're not an admin.",
        "PASSWORD_MISSING": "You must enable 2FA in order to transfer ownership of a channel.",
        "PASSWORD_TOO_FRESH_%d": "The password was modified less than 24 hours ago, try again in %d seconds.",
        "SESSION_TOO_FRESH_%d": "This session was created less than 24 hours ago, try again in %d seconds.",
        "MEGAGROUP_REQUIRED": "You can only use this method on a supergroup.",
        "FILE_REFERENCE_INVALID": "The specified file reference is invalid.",
        "PHOTO_CROP_SIZE_SMALL": "Photo is too small.",
        "PHOTO_EXT_INVALID": "The extension of the photo is invalid.",
        "PHOTO_INVALID": "Photo invalid.",
        "MESSAGE_ID_INVALID": "The provided message id is invalid.",
        "USER_BANNED_IN_CHANNEL": "You're banned from sending messages in supergroups/channels.",
        "MESSAGE_IDS_EMPTY": "No message ids were provided.",
        "USER_NOT_PARTICIPANT": "You're not a member of this supergroup/channel.",
        "CHAT_INVALID": "Invalid chat.",
        "USER_BOT": "Bots can only be admins in channels.",
        "USER_KICKED": "This user was kicked from this supergroup/channel.",
        "INVITE_HASH_EMPTY": "The invite hash is empty.",
        "INVITE_HASH_INVALID": "The invite hash is invalid.",
        "INVITE_REQUEST_SENT": "You have successfully requested to join this chat or channel.",
        "USER_ALREADY_PARTICIPANT": "The user is already in the group.",
        "USER_CHANNELS_TOO_MUCH": "One of the users you tried to add is already in too many channels/supergroups.",
        "BROADCAST_ID_INVALID": "Broadcast ID invalid.",
        "LINK_NOT_MODIFIED": "Discussion link not modified.",
        "MEGAGROUP_ID_INVALID": "Invalid supergroup ID.",
        "MEGAGROUP_PREHISTORY_HIDDEN": "Group with hidden history for new members can't be set as discussion groups.",
        "CHAT_LINK_EXISTS": "The chat is public, you can't hide the history to new users.",
        "SECONDS_INVALID": "Invalid duration provided.",
        "CONTACT_ADD_MISSING": "Contact to add is missing.",
        "CONTACT_ID_INVALID": "The provided contact ID is invalid.",
        "CONTACT_REQ_MISSING": "Missing contact request.",
        "CONTACT_NAME_EMPTY": "Contact name empty.",
        "GEO_POINT_INVALID": "Invalid geoposition provided.",
        "TYPES_EMPTY": "No top peer type was provided.",
        "CONNECTION_LAYER_INVALID": "Layer invalid.",
        "USERNAME_NOT_OCCUPIED": "The provided username is not occupied.",
        "QUERY_TOO_SHORT": "The query string is too short.",
        "SEARCH_QUERY_EMPTY": "The search query is empty.",
        "FOLDER_ID_EMPTY": "An empty folder ID was specified.",
        "FOLDER_ID_INVALID": "Invalid folder ID.",
        "USER_INVALID": "Invalid user provided.",
        "CONNECTION_API_ID_INVALID": "The provided API id is invalid.",
        "CONNECTION_APP_VERSION_EMPTY": "App version is empty.",
        "DATA_INVALID": "Encrypted data invalid.",
        "CDN_METHOD_INVALID": "You can't call this method in a CDN DC.",
        "INVITE_HASH_EXPIRED": "The invite link has expired.",
        "DATE_EMPTY": "Date empty.",
        "PERSISTENT_TIMESTAMP_EMPTY": "Persistent timestamp empty.",
        "PERSISTENT_TIMESTAMP_INVALID": "Persistent timestamp invalid.",
        "LANG_PACK_INVALID": "The provided language pack is invalid.",
        "ENCRYPTION_ALREADY_ACCEPTED": "Secret chat already accepted.",
        "ENCRYPTION_ALREADY_DECLINED": "The secret chat was already declined.",
        "USER_IS_BLOCKED": "You were blocked by this user.",
        "YOU_BLOCKED_USER": "You blocked this user.",
        "USER_NOT_MUTUAL_CONTACT": "The provided user is not a mutual contact.",
        "USERS_TOO_FEW": "Not enough users (to create a chat, for example).",
        "INVITE_REVOKED_MISSING": "The specified invite link was already revoked or is invalid.",
        "CHAT_ID_EMPTY": "The provided chat ID is empty.",
        "ENCRYPTION_ID_INVALID": "The provided secret chat ID is invalid.",
        "CHAT_ABOUT_NOT_MODIFIED": "About text has not changed.",
        "BANNED_RIGHTS_INVALID": "You provided some invalid flags in the banned rights.",
        "UNTIL_DATE_INVALID": "Invalid until date provided.",
        "MESSAGE_NOT_MODIFIED": "The provided message data is identical to the previous message data, the message wasn't modified.",
        "BUTTON_DATA_INVALID": "The data of one or more of the buttons you provided is invalid.",
        "BUTTON_TYPE_INVALID": "The type of one or more of the buttons you provided is invalid.",
        "BUTTON_URL_INVALID": "Button URL invalid.",
        "ENTITIES_TOO_LONG": "You provided too many styled message entities.",
        "MEDIA_CAPTION_TOO_LONG": "The caption is too long.",
        "MEDIA_GROUPED_INVALID": "You tried to send media of different types in an album.",
        "MEDIA_NEW_INVALID": "The new media is invalid.",
        "MEDIA_PREV_INVALID": "Previous media invalid.",
        "MESSAGE_EDIT_TIME_EXPIRED": "You can't edit this message anymore, too much time has passed since its creation.",
        "MESSAGE_EMPTY": "The provided message is empty.",
        "MESSAGE_TOO_LONG": "The provided message is too long.",
        "REPLY_MARKUP_INVALID": "The provided reply markup is invalid.",
        "SCHEDULE_DATE_INVALID": "Invalid schedule date provided.",
        "EXPIRE_DATE_INVALID": "The specified expiration date is invalid.",
        "USAGE_LIMIT_INVALID": "The specified usage limit is invalid.",
        "STICKER_ID_INVALID": "The provided sticker ID is invalid.",
        "BROADCAST_PUBLIC_VOTERS_FORBIDDEN": "You can't forward polls with public voters.",
        "CHAT_RESTRICTED": "You can't send messages in this chat, you were restricted.",
        "GROUPED_MEDIA_INVALID": "Invalid grouped media.",
        "MEDIA_EMPTY": "The provided media object is invalid.",
        "QUIZ_ANSWER_MISSING": "You can forward a quiz while hiding the original author only after choosing an option in the quiz.",
        "RANDOM_ID_INVALID": "A provided random ID is invalid.",
        "SCHEDULE_DATE_TOO_LATE": "You can't schedule a message this far in the future.",
        "SCHEDULE_TOO_MUCH": "There are too many scheduled messages.",
        "SEND_AS_PEER_INVALID": "You can't send messages as the specified peer.",
        "SLOWMODE_MULTI_MSGS_DISABLED": "Slowmode is enabled, you cannot forward multiple messages to this group.",
        "USER_IS_BOT": "Bots can't send messages to other bots.",
        "BOT_RESPONSE_TIMEOUT": "A timeout occurred while fetching data from the bot.",
        "SEARCH_WITH_LINK_NOT_SUPPORTED": "You cannot provide a search query and an invite link at the same time.",
        "RANDOM_LENGTH_INVALID": "Random length invalid.",
        "OFFSET_PEER_ID_INVALID": "The provided offset peer is invalid.",
        "SHA256_HASH_INVALID": "The provided SHA256 hash is invalid.",
        "ADMIN_ID_INVALID": "The specified admin ID is invalid.",
        "USER_BOT_REQUIRED": "This method can only be called by a bot.",
        "BOT_INLINE_DISABLED": "This bot can't be used in inline mode.",
        "BOT_INVALID": "This is not a valid bot.",
        "CHAT_TOO_BIG": "This method is not available for groups with more than chat_read_mark_size_threshold members, see client configuration ».",
        "FILTER_NOT_SUPPORTED": "The specified filter cannot be used in this context.",
        "WC_CONVERT_URL_INVALID": "WC convert URL invalid.",
        "IMPORT_FILE_INVALID": "The specified chat export file is invalid.",
        "IMPORT_FORMAT_UNRECOGNIZED": "The specified chat export file was exported from an unsupported chat app.",
        "STICKERSET_INVALID": "The provided sticker set is invalid.",
        "MSG_WAIT_FAILED": "A waiting call returned an error.",
        "MAX_QTS_INVALID": "The specified max_qts is invalid.",
        "DH_G_A_INVALID": "g_a invalid.",
        "GIF_ID_INVALID": "The provided GIF ID is invalid.",
        "DATA_TOO_LONG": "Data too long.",
        "ENCRYPTION_DECLINED": "The secret chat was declined.",
        "FILE_EMTPY": "An empty file was provided.",
        "MD5_CHECKSUM_INVALID": "The MD5 checksums do not match.",
        "INLINE_RESULT_EXPIRED": "The inline query expired.",
        "QUERY_ID_EMPTY": "The query ID is empty.",
        "RESULT_ID_EMPTY": "Result ID empty.",
        "WEBPAGE_CURL_FAILED": "Failure while fetching the webpage with cURL.",
        "WEBPAGE_MEDIA_EMPTY": "Webpage media empty.",
        "BOT_PAYMENTS_DISABLED": "Please enable bot payments in botfather before calling this method.",
        "CHAT_FORWARDS_RESTRICTED": "You can't forward messages from a protected chat.",
        "CURRENCY_TOTAL_AMOUNT_INVALID": "The total amount of all prices is invalid.",
        "EMOTICON_INVALID": "The specified emoji is invalid.",
        "EXTERNAL_URL_INVALID": "External URL invalid.",
        "FILE_PARTS_INVALID": "The number of file parts is invalid.",
        "FILE_PART_LENGTH_INVALID": "The length of a file part is invalid.",
        "FILE_REFERENCE_EMPTY": "An empty file reference was specified.",
        "FILE_REFERENCE_EXPIRED": "File reference expired, it must be refetched as described in the documentation.",
        "GAME_BOT_INVALID": "Bots can't send another bot's game.",
        "IMAGE_PROCESS_FAILED": "Failure while processing image.",
        "MEDIA_INVALID": "Media invalid.",
        "PAYMENT_PROVIDER_INVALID": "The specified payment provider is invalid.",
        "PHOTO_INVALID_DIMENSIONS": "The photo dimensions are invalid.",
        "PHOTO_SAVE_FILE_INVALID": "Internal issues, try again later.",
        "POLL_ANSWERS_INVALID": "Invalid poll answers were provided.",
        "POLL_ANSWER_INVALID": "One of the poll answers is not acceptable.",
        "POLL_OPTION_DUPLICATE": "Duplicate poll options provided.",
        "POLL_OPTION_INVALID": "Invalid poll option provided.",
        "POLL_QUESTION_INVALID": "One of the poll questions is not acceptable.",
        "QUIZ_CORRECT_ANSWERS_EMPTY": "No correct quiz answer was specified.",
        "QUIZ_CORRECT_ANSWERS_TOO_MUCH": "You specified too many correct answers in a quiz, quizzes can only have one right answer!",
        "QUIZ_CORRECT_ANSWER_INVALID": "An invalid value was provided to the correct_answers field.",
        "QUIZ_MULTIPLE_INVALID": "Quizzes can't have the multiple_choice flag set!",
        "REPLY_MARKUP_BUY_EMPTY": "Reply markup for buy button empty.",
        "SCHEDULE_BOT_NOT_ALLOWED": "Bots cannot schedule messages.",
        "TTL_MEDIA_INVALID": "Invalid media Time To Live was provided.",
        "VIDEO_CONTENT_TYPE_INVALID": "The video's content type is invalid.",
        "BOT_DOMAIN_INVALID": "Bot domain invalid.",
        "ENTITY_MENTION_USER_INVALID": "You mentioned an invalid user.",
        "FROM_MESSAGE_BOT_DISABLED": "Bots can't use fromMessage min constructors.",
        "PINNED_DIALOGS_TOO_MUCH": "Too many pinned dialogs.",
        "REPLY_MARKUP_TOO_LONG": "The specified reply_markup is too long.",
        "SCHEDULE_STATUS_PRIVATE": "Can't schedule until user is online, if the user's last seen timestamp is hidden by their privacy settings.",
        "MULTI_MEDIA_TOO_LONG": "Too many media files for album.",
        "RANDOM_ID_EMPTY": "Random ID empty.",
        "REACTION_EMPTY": "Empty reaction provided.",
        "REACTION_INVALID": "The specified reaction is invalid.",
        "MESSAGE_POLL_CLOSED": "Poll closed.",
        "OPTIONS_TOO_MUCH": "Too many options provided.",
        "OPTION_INVALID": "Invalid option selected.",
        "REVOTE_NOT_ALLOWED": "You cannot change your vote.",
        "URL_INVALID": "Invalid URL provided.",
        "ERROR_TEXT_EMPTY": "The provided error message is empty.",
        "EMOJI_INVALID": "The specified theme emoji is valid.",
        "EMOJI_NOT_MODIFIED": "The theme wasn't changed.",
        "BOT_SCORE_NOT_MODIFIED": "The score wasn't modified.",
        "SCORE_INVALID": "The specified game score is invalid.",
        "TTL_PERIOD_INVALID": "The specified TTL period is invalid.",
        "ARTICLE_TITLE_EMPTY": "The title of the article is empty.",
        "AUDIO_CONTENT_URL_EMPTY": "The remote URL specified in the content field is empty.",
        "AUDIO_TITLE_EMPTY": "An empty audio title was provided.",
        "DOCUMENT_INVALID": "The specified document is invalid.",
        "FILE_CONTENT_TYPE_INVALID": "File content-type is invalid.",
        "FILE_TITLE_EMPTY": "An empty file title was specified.",
        "GIF_CONTENT_TYPE_INVALID": "GIF content-type invalid.",
        "NEXT_OFFSET_INVALID": "The specified offset is longer than 64 bytes.",
        "PHOTO_CONTENT_TYPE_INVALID": "Photo mime-type invalid.",
        "PHOTO_CONTENT_URL_EMPTY": "Photo URL invalid.",
        "PHOTO_THUMB_URL_EMPTY": "Photo thumbnail URL is empty.",
        "RESULTS_TOO_MUCH": "Too many results were provided.",
        "RESULT_ID_DUPLICATE": "You provided a duplicate result ID.",
        "RESULT_TYPE_INVALID": "Result type invalid.",
        "SEND_MESSAGE_MEDIA_INVALID": "Invalid media provided.",
        "SEND_MESSAGE_TYPE_INVALID": "The message type is invalid.",
        "START_PARAM_INVALID": "Start parameter invalid.",
        "STICKER_DOCUMENT_INVALID": "The specified sticker document is invalid.",
        "VIDEO_TITLE_EMPTY": "The specified video title is empty.",
        "WEBDOCUMENT_INVALID": "Invalid webdocument URL provided.",
        "WEBDOCUMENT_MIME_INVALID": "Invalid webdocument mime type provided.",
        "WEBDOCUMENT_SIZE_TOO_BIG": "Webdocument is too big!",
        "WEBDOCUMENT_URL_INVALID": "The specified webdocument URL is invalid.",
        "START_PARAM_EMPTY": "The start parameter is empty.",
        "START_PARAM_TOO_LONG": "Start parameter is too long.",
        "IMPORT_ID_INVALID": "The specified import ID is invalid.",
        "BOT_ONESIDE_NOT_AVAIL": "Bots can't pin messages in PM just for themselves.",
        "PIN_RESTRICTED": "You can't pin messages.",
        "BOT_MISSING": "This method can only be run by a bot.",
        "BANK_CARD_NUMBER_INVALID": "The specified card number is invalid.",
        "CALL_ALREADY_ACCEPTED": "The call was already accepted.",
        "CALL_ALREADY_DECLINED": "The call was already declined.",
        "CALL_PEER_INVALID": "The provided call peer object is invalid.",
        "CALL_PROTOCOL_FLAGS_INVALID": "Call protocol flags invalid.",
        "USER_VOLUME_INVALID": "The specified user volume is invalid.",
        "GROUPCALL_INVALID": "The specified group call is invalid.",
        "GROUPCALL_JOIN_MISSING": "You haven't joined this group call.",
        "INVITE_FORBIDDEN_WITH_JOINAS": "If the user has anonymously joined a group call as a channel, they can't invite other users to the group call because that would cause deanonymization, because the invite would be sent using the original user ID, not the anonymized channel ID.",
        "USER_ALREADY_INVITED": "You have already invited this user.",
        "GROUPCALL_SSRC_DUPLICATE_MUCH": "The app needs to retry joining the group call with a new SSRC value.",
        "PARTICIPANT_VERSION_OUTDATED": "The other participant does not use an up to date telegram client with support for calls.",
        "DATA_JSON_INVALID": "The provided JSON data is invalid.",
        "GROUPCALL_NOT_MODIFIED": "Group call settings weren't modified.",
        "MAX_ID_INVALID": "The provided max ID is invalid.",
        "ALBUM_PHOTOS_TOO_MANY": "You have uploaded too many profile photos, delete some before retrying.",
        "LOCATION_INVALID": "The provided location is invalid.",
        "PHOTO_ID_INVALID": "Photo ID invalid.",
        "PHOTO_CROP_FILE_MISSING": "Photo crop file missing.",
        "PHOTO_FILE_MISSING": "Profile photo file missing.",
        "VIDEO_FILE_INVALID": "The specified video file is invalid.",
        "BROADCAST_REQUIRED": "This method can only be called on a channel, please use stats.getMegagroupStats for supergroups.",
        "GRAPH_EXPIRED_RELOAD": "This graph has expired, please obtain a new graph token.",
        "GRAPH_INVALID_RELOAD": "Invalid graph token provided, please reload the stats and provide the updated token.",
        "GRAPH_OUTDATED_RELOAD": "The graph is outdated, please get a new async token using stats.getBroadcastStats.",
        "STICKERPACK_STICKERS_TOO_MUCH": "There are too many stickers in this stickerpack, you can't add any more.",
        "STICKERS_TOO_MUCH": "There are too many stickers in this stickerpack, you can't add any more.",
        "STICKER_PNG_NOPNG": "One of the specified stickers is not a valid PNG file.",
        "STICKER_TGS_NOTGS": "Invalid TGS sticker provided.",
        "STICKER_INVALID": "The provided sticker is invalid.",
        "SHORT_NAME_INVALID": "The specified short name is invalid.",
        "SHORT_NAME_OCCUPIED": "The specified short name is already in use.",
        "PACK_SHORT_NAME_INVALID": "Short pack name invalid.",
        "PACK_SHORT_NAME_OCCUPIED": "A stickerpack with this name already exists.",
        "PACK_TITLE_INVALID": "The stickerpack title is invalid.",
        "STICKERS_EMPTY": "No sticker provided.",
        "STICKER_EMOJI_INVALID": "Sticker emoji invalid.",
        "STICKER_FILE_INVALID": "Sticker file invalid.",
        "STICKER_GIF_DIMENSIONS": "The specified video sticker has invalid dimensions.",
        "STICKER_PNG_DIMENSIONS": "Sticker png dimensions invalid.",
        "STICKER_TGS_NODOC": "Incorrect document type for sticker.",
        "STICKER_THUMB_PNG_NOPNG": "Incorrect stickerset thumb file provided, PNG / WEBP expected.",
        "STICKER_THUMB_TGS_NOTGS": "Incorrect stickerset TGS thumb file provided.",
        "STICKER_VIDEO_BIG": "The specified video sticker is too big.",
        "STICKER_VIDEO_NOWEBM": "The specified video sticker is not in webm format.",
        "TITLE_INVALID": "The specified stickerpack title is invalid.",
        "RANGES_INVALID": "Invalid range provided.",
        "RSA_DECRYPT_FAILED": "Internal RSA decryption failed.",
        "FILE_REFERENCE_*": "The file reference expired, it must be refreshed.",
        "FILE_ID_INVALID": "The provided file id is invalid.",
        "LIMIT_INVALID": "The provided limit is invalid.",
        "OFFSET_INVALID": "The provided offset is invalid.",
        "FILE_PART_EMPTY": "The provided file part is empty.",
        "FILE_PART_INVALID": "The file part number is invalid.",
        "FILE_PART_SIZE_CHANGED": "Provided file part size has changed.",
        "FILE_PART_SIZE_INVALID": "The provided file part size is invalid.",
        "FILE_PART_TOO_BIG": "The uploaded file part is too big."
    },
    "403": {
        "TAKEOUT_REQUIRED": "A takeout session has to be initialized, first.",
        "SENSITIVE_CHANGE_FORBIDDEN": "You can't change your sensitive content settings.",
        "CHAT_WRITE_FORBIDDEN": "You can't write in this chat.",
        "USER_BOT_INVALID": "This method can only be called by a bot.",
        "MESSAGE_DELETE_FORBIDDEN": "You can't delete one of the messages you tried to delete, most likely because it is a service message.",
        "CHAT_ADMIN_INVITE_REQUIRED": "You do not have the rights to do this.",
        "RIGHT_FORBIDDEN": "Your admin rights do not allow you to do this.",
        "USER_CHANNELS_TOO_MUCH": "One of the users you tried to add is already in too many channels/supergroups.",
        "USER_NOT_MUTUAL_CONTACT": "The provided user is not a mutual contact.",
        "USER_PRIVACY_RESTRICTED": "The user's privacy settings do not allow you to do this.",
        "USER_RESTRICTED": "You're spamreported, you can't create channels or chats.",
        "CHANNEL_PUBLIC_GROUP_NA": "channel/supergroup not available.",
        "USER_INVALID": "Invalid user provided.",
        "EDIT_BOT_INVITE_FORBIDDEN": "Normal users can't edit invites that were created by bots.",
        "CHAT_ADMIN_REQUIRED": "You must be an admin in this chat to do this.",
        "INLINE_BOT_REQUIRED": "Only the inline bot can edit message.",
        "MESSAGE_AUTHOR_REQUIRED": "Message author required.",
        "CHAT_SEND_GAME_FORBIDDEN": "You can't send a game to this chat.",
        "CHAT_SEND_GIFS_FORBIDDEN": "You can't send gifs in this chat.",
        "CHAT_SEND_MEDIA_FORBIDDEN": "You can't send media in this chat.",
        "CHAT_SEND_POLL_FORBIDDEN": "You can't send polls in this chat.",
        "CHAT_SEND_STICKERS_FORBIDDEN": "You can't send stickers in this chat.",
        "USER_IS_BLOCKED": "You were blocked by this user.",
        "BROADCAST_FORBIDDEN": "Participants of polls in channels should stay anonymous.",
        "POLL_VOTE_REQUIRED": "Cast a vote in the poll before calling this method.",
        "USER_DELETED": "You can't send this secret message because the other participant deleted their account.",
        "CHAT_SEND_INLINE_FORBIDDEN": "You can't send inline messages in this group.",
        "GROUPCALL_FORBIDDEN": "The group call has already ended.",
        "PARTICIPANT_JOIN_MISSING": "Trying to enable a presentation, when the user hasn't joined the Video Chat with phone.joinGroupCall."
    },
    "406": {
        "PHONE_NUMBER_INVALID": "The phone number is invalid.",
        "FRESH_RESET_AUTHORISATION_FORBIDDEN": "You can't logout other sessions if less than 24 hours have passed since you logged on the current session.",
        "FRESH_CHANGE_PHONE_FORBIDDEN": "You can't change phone number right after logging in, please wait at least 24 hours.",
        "SEND_CODE_UNAVAILABLE": "Returned when all available options for this type of number were already used (e.g. flash-call, then SMS, then this error might be returned to trigger a second resend).",
        "USER_RESTRICTED": "You're spamreported, you can't create channels or chats.",
        "CHANNEL_TOO_LARGE": "Channel is too large to be deleted; this error is issued when trying to delete channels with more than 1000 members (subject to change).",
        "FRESH_CHANGE_ADMINS_FORBIDDEN": "You were just elected admin, you can't add or modify other admins yet.",
        "CHANNEL_PRIVATE": "You haven't joined this channel/supergroup.",
        "INVITE_HASH_EXPIRED": "The invite link has expired.",
        "STICKERSET_OWNER_ANONYMOUS": "Provided stickerset can't be installed as group stickerset to prevent admin deanonymization.",
        "USERPIC_PRIVACY_REQUIRED": "You need to disable privacy settings for your profile picture in order to make your geolocation public.",
        "USERPIC_UPLOAD_REQUIRED": "You must have a profile picture to publish your geolocation.",
        "CHAT_FORWARDS_RESTRICTED": "You can't forward messages from a protected chat.",
        "STICKERSET_INVALID": "The provided sticker set is invalid.",
        "PREVIOUS_CHAT_IMPORT_ACTIVE_WAIT_%dMIN": "Import for this chat is already in progress, wait %d minutes before starting a new one.",
        "FILEREF_UPGRADE_NEEDED": "The client has to be updated in order to support file references."
    },
    "420": {
        "2FA_CONFIRM_WAIT_%d": "Since this account is active and protected by a 2FA password, we will delete it in 1 week for security purposes. You can cancel this process at any time, you'll be able to reset your account in %d seconds.",
        "TAKEOUT_INIT_DELAY_%d": "Wait %d seconds before initializing takeout.",
        "SLOWMODE_WAIT_%d": "Slowmode is enabled in this chat: wait %d seconds before sending another message to this chat."
    },
    "500": {
        "SIGN_IN_FAILED": "Failure while signing in.",
        "CHAT_ID_GENERATE_FAILED": "Failure while generating the chat ID.",
        "RANDOM_ID_DUPLICATE": "You provided a random ID that was already used.",
        "CALL_OCCUPY_FAILED": "The call failed because the user is already making another call.",
        "PARTICIPANT_CALL_FAILED": "Failure while making call.",
        "PERSISTENT_TIMESTAMP_OUTDATED": "Channel internal replication issues, try again later (treat this like an RPC_CALL_FAIL)."
    },
    "-503": {
        "Timeout": "Timeout while fetching data."
    }
}